Repository MetaModels/core, pull requests merged in 2018-03, with the labels that each got.

#1196 [RTM] Hotfix for edit/override all in DCG
  src/MetaModels/DcGeneral/Data/Driver.php
  src/MetaModels/DcGeneral/Events/Table/InputScreenCondition/Subscriber.php
  src/MetaModels/IItem.php
  src/MetaModels/IMetaModel.php
  src/MetaModels/Item.php
  src/MetaModels/MetaModel.php
Labels: DC_General, enhancement

#1216 [RTM] hotfix updating PHP version
  .travis.yml
  composer.json
Labels: enhancement

#1217 [RTM] Hotfix file sorting by file name
  src/MetaModels/Helper/ToolboxFile.php
Labels: bug

#1204 [RTM] hotfix issue #1203 add all_langs option
  contao/dca/tl_metamodel_filtersetting.php
  src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php
Labels: bug

#1229 [RTM] fix SubPalettesSubscriber
  src/MetaModels/DcGeneral/Events/Table/FilterSetting/SubPaletteSubscriber.php
Labels: bug
